/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-variant': '#d5e3fd',
        'surface-dim': '#ccdbf4',
        tertiary: '#303539',
        'on-error-container': '#93000a',
        'surface-container-high': '#dde9ff',
        'surface-container': '#e6eeff',
        'on-primary-fixed': '#001453',
        'on-surface-variant': '#444653',
        'surface-tint': '#3755c3',
        'secondary-fixed-dim': '#a4c9ff',
        background: '#f8f9ff',
        'on-background': '#0d1c2f',
        'on-secondary-fixed': '#001c39',
        'inverse-surface': '#233144',
        'on-primary-container': '#a8b8ff',
        'secondary-fixed': '#d4e3ff',
        secondary: '#0060ac',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#ebf1ff',
        'on-error': '#ffffff',
        surface: '#f8f9ff',
        'error-container': '#ffdad6',
        error: '#ba1a1a',
        'outline-variant': '#c4c5d5',
        'primary-fixed-dim': '#b8c4ff',
        'inverse-primary': '#b8c4ff',
        'primary-container': '#1e40af',
        'tertiary-fixed-dim': '#c3c7cb',
        'on-secondary-fixed-variant': '#004883',
        'surface-container-highest': '#d5e3fd',
        'tertiary-fixed': '#dfe3e7',
        'on-primary-fixed-variant': '#173bab',
        outline: '#757684',
        'on-tertiary': '#ffffff',
        primary: '#00288e',
        'on-tertiary-container': '#b8bcc0',
        'primary-fixed': '#dde1ff',
        'on-surface': '#0d1c2f',
        'tertiary-container': '#474c4f',
        'on-secondary': '#ffffff',
        'surface-bright': '#f8f9ff',
        'on-secondary-container': '#003c70',
        'surface-container-low': '#eff4ff',
        'secondary-container': '#64a8fe',
        'on-tertiary-fixed-variant': '#43474b',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#171c1f',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        lg: '24px',
        base: '4px',
        gutter: '24px',
        xl: '32px',
        xs: '4px',
        sm: '8px',
        '2xl': '48px',
        '3xl': '64px',
        md: '16px',
        'container-max': '1280px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-xl-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '200% 0' },
          '100%': { backgroundPosition: '-200% 0' },
        },
        fadeIn: {
          from: { opacity: '0', transform: 'translateY(10px)' },
          to: { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        shimmer: 'shimmer 1.5s infinite',
        'fade-in': 'fadeIn 0.6s ease-out forwards',
      },
    },
  },
  plugins: [],
}
